### ISSUE TITLE
Incompatible JavaSE versions when uploading to LARS with larsClient

### ISSUE THREAD

**Issue by jbodwell** [WASdev/tool.lars#126]
We are using LARS v1.1.0 and attempting to upload the following features which came in the wlp-featureRepo-8.5.5.9.zip released with WAS LP 8.5.5.9.

com.ibm.websphere.appserver.apiDiscovery-1.0.esa  
com.ibm.websphere.appserver.jaxws-2.2.esa
com.ibm.websphere.appserver.beanValidationCore-1.0.esa  
com.ibm.websphere.appserver.jpa-2.0.esa
com.ibm.websphere.appserver.clusterMember-1.0.esa  
com.ibm.websphere.appserver.openid-2.0.esa
com.ibm.websphere.appserver.collectiveMember-1.0.esa  
com.ibm.websphere.appserver.openidConnectClient-1.0.esa
com.ibm.websphere.appserver.iiopcommon-1.0.esa  
com.ibm.websphere.appserver.servlet-3.0.esa
com.ibm.websphere.appserver.jaxb-2.2.esa  
com.ibm.websphere.appserver.servlet-3.1.esa
com.ibm.websphere.appserver.jaxrs.common-2.0.esa

We get the following error when attempting to upload to LARS using larsClient:

ESA com.ibm.websphere.appserver.jaxrs.common-2.0.esa is invalid, two bundles require incompatible JavaSE versions

I’ve tried upgraded to java 8 (previously we were at java7) and that doesn’t help.

**Comment by Azquelt** [comment]
Looking into this, we did previously have issues with features which required Java 8, but thought we'd fixed that in 1.1.

**Comment by Azquelt** [comment]
I can't reproduce the problem with 1.1. Could you make sure you're using the 1.1 client as well as the 1.1 server? It's the client that does the check.

The latest client can be downloaded from https://developer.ibm.com/wasdev/downloads/#asset/tools-Liberty_Asset_Repository_Service_Client

The 1.0 client outputs the error you describe.

**Comment by jbodwell** [comment]
You're right - I must not have installed the latest larsClient. It's now working as expected.
