### ISSUE TITLE
Document how to set up LARS behind a reverse proxy

### ISSUE THREAD

**Issue by Azquelt** [WASdev/tool.lars#144]
When setting up LARS behind a reverse proxy, it needs to know it's external URL so that it can compute correct URLs for attachments.

It's possible for the user to configure this by setting a JNDI entry named "lars/URLBase". There's an example of how to do this in the server.xml, but we don't document it.

We should have documentation on how to set this up. Notably there's a specific gotcha that if you set URLBase to "http://example.com", you have to set the repository URL in installUtility to "http://example.com/ma/v1".

**Comment by BillyD73** [comment]
@Azquelt  Can we close this now?

**Comment by Azquelt** [comment]
Depends, have you done it?

**Comment by rickettmwork** [comment]
@Azquelt No.  Do you know how to set up LARS behind a reverse proxy?

**Comment by Azquelt** [comment]
Stretching my memory somewhat and then digging through the code I arrived at https://github.com/WASdev/tool.lars/blob/master/server/src/main/java/com/ibm/ws/lars/rest/Configuration.java#L64

Based on that and looking at bit further, I found that we do actually say how to do this in the comments in server.xml: https://github.com/WASdev/tool.lars/blob/master/server/config/server.xml#L63-L64

**Comment by rickettmwork** [comment]
Thanks
