### ISSUE TITLE
Non-apache licensed files?

### ISSUE THREAD

**Issue by hughesj** [WASdev/tool.lars#159]
Is there a need to include the ILAN license any longer?

https://github.com/WASdev/tool.lars/tree/master/upload-lib/src/fat/testResources/com.ibm.websphere.appserver.json-1.0.esa/wlp/lafiles

**Comment by Azquelt** [comment]
These are test resources to ensure the uploader handles .esas correctly. Some of the rest resources are representative of product .esas, so they have appropriate license files, even though that license isn't applied to any of the code in the repository.
