### ISSUE TITLE
Root user requirements

### ISSUE THREAD

**Issue by cycotron69** [WASdev/tool.lars#177]
WLP for LARS needs to be run as ROOT user, else I receive file access permission errors when uploading the features using the client.  This is against best practice when hosting a LARS in kubernetes platform as the WLP in the container needs to run as non-root user for security considerations.

**Comment by pnickoll** [comment]
We will investigate this....

**Comment by rickettmwork** [comment]
Hi @cycotron69 

I've not been able to reproduce this - I've got a docker container running WLP as a non-root user with LARS, and have been able to upload assets successfully.

Could you provide the exact errors you're seeing (including stack trace if any) please?

Thanks

**Comment by rickettmwork** [comment]
Hi @cycotron69 

I am closing this issue as we have not heard back.  If this is still a problem for you please re-open with more details

Thanks
