### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by rickettmwork** [WASdev/tool.lars#178]
There are a number of places where LARS is using deprecated code, resulting in lots of warnings when compiling.

These should be fixed before the deprecated methods are removed.

There are also a lot of deprecation warnings in the test code.

**Comment by rickettmwork** [comment]
This page will help with some of them https://stackoverflow.com/questions/42599422/warning-options-bootstrap-class-path-not-set-in-conjunction-with-source-1-7

**Comment by BillyD73** [comment]
This was fixed by #194
