### ISSUE TITLE
Need to set auth mechanism to "PLAIN" for MongoDB login

### ISSUE THREAD

**Issue by SteveFreeman** [WASdev/tool.lars#191]
This works from the command line but not from LARS because the mechanism defaults to SCRAM-SHA-1:

```
mongo --host s50727.mdb-50727-9e7d-dev.svc.k8svc.ford.com --port 27017 --tls --tlsCAFile mongo-dev-cert.pem --authenticationDatabase $external --authenticationMechanism "PLAIN" --username sfreeman --password
```

Error in log:

```
Command failed with error 2 (BadValue): 'Unsupported mechanism 'SCRAM-SHA-1' on authentication database '$external'' on server s50727.mdb-50727-9e7d-dev.svc.k8svc.ford.com:27017. The full response is {"ok": 0.0, "errmsg": "Unsupported mechanism 'SCRAM-SHA-1' on authentication database '$external'", "code": 2, "codeName": "BadValue", "operationTime": {"$timestamp": {"t": 1579194876, "i": 1}}, "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1579194876, "i": 1}}, "signature": {"hash": {"$binary": "ESxpIuOa1qFOZ6/HyHoSzBmKp5o=", "$type": "00"}, "keyId": {"$numberLong": "6781535884714967042"}}}}```

**Comment by rickettmwork** [comment]
We will investigate this to see if it is something that we can make LARS support

**Comment by SteveFreeman** [comment]
Please see this document:
http://mongodb.github.io/mongo-java-driver/3.12/javadoc/com/mongodb/MongoCredential.html#withMechanism(com.mongodb.AuthenticationMechanism)

Instead of `MongoCredential.createCredential(user, authDbName, password.toCharArray());` you should use `MongoCredential.createCredential(user, authDbName, password.toCharArray()).withMechanism(MongoCredential.PLAIN_MECHANISM);`

Or set up a system property for the applicable values to pass in bootstrap.properties.

**Comment by rickettmwork** [comment]
Hi Steve

Would you be able to test this PR: https://github.com/WASdev/tool.lars/pull/192 to make sure that it works for you?
You will need to add `lars.mongo.authMechanism=PLAIN` to your bootstrap.properties

We do not have MongoDB Enterprise or an LDAP server so are stuggling to find a way to verify this.

Thanks
Mike

**Comment by SteveFreeman** [comment]
I should be able to do some testing later today.  Just one question:  How do I pull the GitHub content with the PR as I haven't done that before?

**Comment by rickettmwork** [comment]
Hi Steve
```
git remote add rickettm https://github.com/rickettmwork/tool.lars
git fetch rickettm
git checkout --track rickettm/191-authMechanisms
```
should do the trick

**Comment by SteveFreeman** [comment]
Thanks, that worked.  I'll test this afternoon and report back.

**Comment by SteveFreeman** [comment]
One last question: What format is the encoded password in?  Would that be {xor} followed by the encoded string or just a base-64 encoded string?

**Comment by SteveFreeman** [comment]
I figured that last question out by myself.

Tested working.  The fix passes the tests for me.

**Comment by rickettmwork** [comment]
Thanks, will get this included in the next release
